name: "Go Formatter"
description: "Automatically formats golang files in pull requests"
author: "sladyn98"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "git-pull-request"
  color: "blue"